---
#

# - name: Stop VMs
#   proxmox_kvm:
#     api_host    : "{{ pve_api_host }}"
#     api_user    : "{{ pve_api_user }}"
#     api_password: "{{ pve_api_pass }}"
#     node        : "{{ rancheros_vm_pve_node }}"
#     name        : "{{ inventory_hostname }}"
#     state       : stopped

# - name: Remove VMs
#   proxmox_kvm:
#     api_host    : "{{ pve_api_host }}"
#     api_user    : "{{ pve_api_user }}"
#     api_password: "{{ pve_api_pass }}"
#     node        : "{{ rancheros_vm_pve_node }}"
#     name        : "{{ inventory_hostname }}"
#     state       : absent
#   register: vmremove_result

# - name: Waiting 10s...
#   pause:
#     seconds: 10
#   when: vmremove_result.changed

- name: Create VM
  proxmox_kvm:
    api_host    : "{{ pve_api_host }}"
    api_user    : "{{ pve_api_user }}"
    api_password: "{{ pve_api_pass }}"
    node        : "{{ rancheros_vm_pve_node }}"
    name        : "{{ inventory_hostname }}"
    vmid        : "{{ rancheros_vm_id }}"
    net         : "{'net0':'virtio,bridge={{ rancheros_vm_bridge }},tag={{ rancheros_vm_tag }}'}"
    virtio      : "{'virtio0':'{{ rancheros_vm_storage }}:{{ rancheros_vm_disksize }}'}"
    ide         : "{'ide0':'{{ rancheros_vm_storage }}:cloudinit,media=cdrom', 'ide2':'local:iso/{{ rancheros_vm_iso }},media=cdrom'}" #,#'ide3':'local:snippets/ros-config/{{ inventory_hostname }}.yaml'}"
    cicustom    : "user=local:snippets/{{ inventory_hostname }}.yaml"
    citype      : 'configdrive2'
    sockets     : "{{ rancheros_vm_sockets }}"
    cores       : "{{ rancheros_vm_cores }}"
    memory      : "{{ rancheros_vm_memory }}"
    storage     : "{{ rancheros_vm_storage }}"
    vga         : "{{ rancheros_vm_vga }}"
    balloon     : 0
    agent       : 1
    ostype      : l26
    autostart   : 1
    onboot      : 1
    #serial      : "{'serial0':'socket'}"
    proxmox_default_behavior: no_defaults
    state       : present
  register: vmcreate_result

- name: Waiting 10s...
  pause:
    seconds: 10
  when: vmcreate_result.changed

- name: Start VM
  proxmox_kvm:
    api_host    : "{{ pve_api_host }}"
    api_user    : "{{ pve_api_user }}"
    api_password: "{{ pve_api_pass }}"
    node        : "{{ rancheros_vm_pve_node }}"
    name        : "{{ inventory_hostname }}"
    state: started
  register: vmstart_result

- name: Waiting 5s...
  pause:
    seconds: 5
  when: vmstart_result.changed

- name: Get VM State
  proxmox_kvm:
    api_host    : "{{ pve_api_host }}"
    api_user    : "{{ pve_api_user }}"
    api_password: "{{ pve_api_pass }}"
    node        : "{{ rancheros_vm_pve_node }}"
    name        : "{{ inventory_hostname }}"
    state: current
  register: vmstate_result