---
#

- name: Remove VMs
  proxmox_kvm:
    api_host    : "{{ pve_api_host }}"
    api_user    : "{{ pve_api_user }}"
    api_password: "{{ pve_api_pass }}"
    node        : "{{ swarm_vm_pve_node }}"
    name        : "{{ inventory_hostname }}"
    state       : absent
  #register: vmstart_result

- name: Create VM
  proxmox_kvm:
    api_host    : "{{ pve_api_host }}"
    api_user    : "{{ pve_api_user }}"
    api_password: "{{ pve_api_pass }}"
    node        : "{{ swarm_vm_pve_node }}"
    name        : "{{ inventory_hostname }}"
    vmid        : "{{ swarm_vm_id }}"
    net         : "{'net0':'virtio,bridge={{ swarm_vm_bridge }},tag={{ swarm_vm_tag }}'}"
    virtio      : "{'virtio0':'{{ swarm_vm_storage }}:{{ swarm_vm_disksize }}'}"
    ide         : "{'ide0':'{{ swarm_vm_storage }}:cloudinit,media=cdrom', 'ide2':'local:iso/{{ swarm_vm_iso }},media=cdrom'}" #,#'ide3':'local:snippets/ros-config/{{ inventory_hostname }}.yaml'}"
    cicustom    : "user=local:snippets/{{ inventory_hostname }}.yaml"
    citype      : 'configdrive2'
    sockets     : "{{ swarm_vm_sockets }}"
    cores       : "{{ swarm_vm_cores }}"
    memory      : "{{ swarm_vm_memory }}"
    storage     : "{{ swarm_vm_storage }}"
    vga         : "{{ swarm_vm_vga }}"
    balloon     : 0
    agent       : 1
    ostype      : l26
    autostart   : 1
    onboot      : 1
    #serial      : "{'serial0':'socket'}"
    proxmox_default_behavior: no_defaults
    state       : present
  register: vmcreate_result

- name: Waiting 10s...
  pause:
    seconds: 10
  when: vmcreate_result.changed

- name: Start VM
  proxmox_kvm:
    api_host    : "{{ pve_api_host }}"
    api_user    : "{{ pve_api_user }}"
    api_password: "{{ pve_api_pass }}"
    node        : "{{ swarm_vm_pve_node }}"
    name        : "{{ inventory_hostname }}"
    state: started
  register: vmstart_result

- name: Waiting 5s...
  pause:
    seconds: 5
  when: vmstart_result.changed

- name: Get VM State
  proxmox_kvm:
    api_host    : "{{ pve_api_host }}"
    api_user    : "{{ pve_api_user }}"
    api_password: "{{ pve_api_pass }}"
    node        : "{{ swarm_vm_pve_node }}"
    name        : "{{ inventory_hostname }}"
    state: current
  register: vmstate_result